# IMPORTING LIBRARIES


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# IMPORTING DATASET

In [2]:
data=pd.read_csv("/content/HeartDisease.csv")

In [3]:
print(data.head())

   age  gender  chest_pain  rest_bps  cholestrol  fasting_blood_sugar  \
0   63       1           3       145         233                    1   
1   37       1           2       130         250                    0   
2   41       0           1       130         204                    0   
3   56       1           1       120         236                    0   
4   57       0           0       120         354                    0   

   rest_ecg  thalach  exer_angina  old_peak  slope  ca  thalassemia  target  
0         0      150            0       2.3      0   0            1       1  
1         1      187            0       3.5      0   0            2       1  
2         0      172            0       1.4      2   0            2       1  
3         1      178            0       0.8      2   0            2       1  
4         1      163            1       0.6      2   0            2       1  


# CHECKING FOR NULLVALUES

In [4]:
data.isnull().sum()

age                    0
gender                 0
chest_pain             0
rest_bps               0
cholestrol             0
fasting_blood_sugar    0
rest_ecg               0
thalach                0
exer_angina            0
old_peak               0
slope                  0
ca                     0
thalassemia            0
target                 0
dtype: int64

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   age                  303 non-null    int64  
 1   gender               303 non-null    int64  
 2   chest_pain           303 non-null    int64  
 3   rest_bps             303 non-null    int64  
 4   cholestrol           303 non-null    int64  
 5   fasting_blood_sugar  303 non-null    int64  
 6   rest_ecg             303 non-null    int64  
 7   thalach              303 non-null    int64  
 8   exer_angina          303 non-null    int64  
 9   old_peak             303 non-null    float64
 10  slope                303 non-null    int64  
 11  ca                   303 non-null    int64  
 12  thalassemia          303 non-null    int64  
 13  target               303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [6]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

# LOGISTIC REGRESSION

In [8]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [10]:
y_pred_train=lr.predict(x_train)

In [11]:
y_pred_test=lr.predict(x_test)

In [12]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

def final_report_train(x,y):
  con_mat=confusion_matrix(x,y)
  accuracy=accuracy_score(x,y)
  cla_rep=classification_report(x,y)
  print(con_mat)
  print(accuracy)
  print(cla_rep)

def final_report_test(x,y):
  con_mat=confusion_matrix(x,y)
  accuracy=accuracy_score(x,y)
  cla_rep=classification_report(x,y)
  print(con_mat)
  print(accuracy)
  print(cla_rep)


In [13]:
final_report_train(y_train,y_pred_train)
final_report_test(y_test,y_pred_test)

[[ 77  29]
 [ 12 124]]
0.8305785123966942
              precision    recall  f1-score   support

           0       0.87      0.73      0.79       106
           1       0.81      0.91      0.86       136

    accuracy                           0.83       242
   macro avg       0.84      0.82      0.82       242
weighted avg       0.83      0.83      0.83       242

[[26  6]
 [ 0 29]]
0.9016393442622951
              precision    recall  f1-score   support

           0       1.00      0.81      0.90        32
           1       0.83      1.00      0.91        29

    accuracy                           0.90        61
   macro avg       0.91      0.91      0.90        61
weighted avg       0.92      0.90      0.90        61



# DECISION TREE

In [14]:
from sklearn.tree import DecisionTreeClassifier
dec=DecisionTreeClassifier(max_depth=3,min_samples_split=4)
dec.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=3, min_samples_split=4)

In [15]:
y_pred_dec_train=dec.predict(x_train)

In [16]:
y_pred_dec_test=dec.predict(x_test)

In [17]:
final_report_train(y_train,y_pred_dec_train)
final_report_test(y_test,y_pred_dec_test)

[[ 92  14]
 [ 27 109]]
0.8305785123966942
              precision    recall  f1-score   support

           0       0.77      0.87      0.82       106
           1       0.89      0.80      0.84       136

    accuracy                           0.83       242
   macro avg       0.83      0.83      0.83       242
weighted avg       0.84      0.83      0.83       242

[[26  6]
 [ 6 23]]
0.8032786885245902
              precision    recall  f1-score   support

           0       0.81      0.81      0.81        32
           1       0.79      0.79      0.79        29

    accuracy                           0.80        61
   macro avg       0.80      0.80      0.80        61
weighted avg       0.80      0.80      0.80        61



# RANDOM FORREST

In [18]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=100) 
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [22]:
y_pred_rfc_train=rfc.predict(x_train)

In [21]:
y_pred_rfc_test=rfc.predict(x_test)

In [23]:
final_report_train(y_train,y_pred_rfc_train)
final_report_test(y_test,y_pred_rfc_test)

[[106   0]
 [  0 136]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       106
           1       1.00      1.00      1.00       136

    accuracy                           1.00       242
   macro avg       1.00      1.00      1.00       242
weighted avg       1.00      1.00      1.00       242

[[26  6]
 [ 0 29]]
0.9016393442622951
              precision    recall  f1-score   support

           0       1.00      0.81      0.90        32
           1       0.83      1.00      0.91        29

    accuracy                           0.90        61
   macro avg       0.91      0.91      0.90        61
weighted avg       0.92      0.90      0.90        61

