In [55]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [86]:
train=pd.read_csv("/content/fordTrain.csv")
test=pd.read_csv("/content/fordTest.csv")

In [87]:
train.head()

TrialID  ObsNum  IsAlert       P1        P2    P3       P4        P5   P6  \
0        0       0        0  34.7406   9.84593  1400  42.8571  0.290601  572   
1        0       1        0  34.4215  13.41120  1400  42.8571  0.290601  572   
2        0       2        0  34.3447  15.18520  1400  42.8571  0.290601  576   
3        0       3        0  34.3421   8.84696  1400  42.8571  0.290601  576   
4        0       4        0  34.3322  14.69940  1400  42.8571  0.290601  576   

        P7  ...     V2   V3       V4  V5    V6  V7    V8  V9  V10      V11  
0  104.895  ...  0.175  752  5.99375   0  2005   0  13.4   0    4  14.8004  
1  104.895  ...  0.455  752  5.99375   0  2007   0  13.4   0    4  14.7729  
2  104.167  ...  0.280  752  5.99375   0  2011   0  13.4   0    4  14.7736  
3  104.167  ...  0.070  752  5.99375   0  2015   0  13.4   0    4  14.7667  
4  104.167  ...  0.175  752  5.99375   0  2017   0  13.4   0    4  14.7757  

[5 rows x 33 columns]

In [88]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 604329 entries, 0 to 604328
Data columns (total 33 columns):
 #   Column   Non-Null Count   Dtype  
---  ------   --------------   -----  
 0   TrialID  604329 non-null  int64  
 1   ObsNum   604329 non-null  int64  
 2   IsAlert  604329 non-null  int64  
 3   P1       604329 non-null  float64
 4   P2       604329 non-null  float64
 5   P3       604329 non-null  int64  
 6   P4       604329 non-null  float64
 7   P5       604329 non-null  float64
 8   P6       604329 non-null  int64  
 9   P7       604329 non-null  float64
 10  P8       604329 non-null  int64  
 11  E1       604329 non-null  float64
 12  E2       604329 non-null  float64
 13  E3       604329 non-null  int64  
 14  E4       604329 non-null  int64  
 15  E5       604329 non-null  float64
 16  E6       604329 non-null  int64  
 17  E7       604329 non-null  int64  
 18  E8       604329 non-null  int64  
 19  E9       604329 non-null  int64  
 20  E10      604329 non-null  

In [89]:
train.isna().sum()

TrialID    0
ObsNum     0
IsAlert    0
P1         0
P2         0
P3         0
P4         0
P5         0
P6         0
P7         0
P8         0
E1         0
E2         0
E3         0
E4         0
E5         0
E6         0
E7         0
E8         0
E9         0
E10        0
E11        0
V1         0
V2         0
V3         0
V4         0
V5         0
V6         0
V7         0
V8         0
V9         0
V10        0
V11        0
dtype: int64

In [ ]:
train=train.dropna()

In [90]:
train.drop("TrialID",axis=1,inplace=True)

In [91]:
print(train["IsAlert"].head())

0    0
1    0
2    0
3    0
4    0
Name: IsAlert, dtype: int64


In [92]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 604329 entries, 0 to 604328
Data columns (total 32 columns):
 #   Column   Non-Null Count   Dtype  
---  ------   --------------   -----  
 0   ObsNum   604329 non-null  int64  
 1   IsAlert  604329 non-null  int64  
 2   P1       604329 non-null  float64
 3   P2       604329 non-null  float64
 4   P3       604329 non-null  int64  
 5   P4       604329 non-null  float64
 6   P5       604329 non-null  float64
 7   P6       604329 non-null  int64  
 8   P7       604329 non-null  float64
 9   P8       604329 non-null  int64  
 10  E1       604329 non-null  float64
 11  E2       604329 non-null  float64
 12  E3       604329 non-null  int64  
 13  E4       604329 non-null  int64  
 14  E5       604329 non-null  float64
 15  E6       604329 non-null  int64  
 16  E7       604329 non-null  int64  
 17  E8       604329 non-null  int64  
 18  E9       604329 non-null  int64  
 19  E10      604329 non-null  int64  
 20  E11      604329 non-null  

In [93]:
x=train.drop("IsAlert",axis=1)


In [94]:
x.head()

ObsNum       P1        P2    P3       P4        P5   P6       P7  P8   E1  \
0       0  34.7406   9.84593  1400  42.8571  0.290601  572  104.895   0  0.0   
1       1  34.4215  13.41120  1400  42.8571  0.290601  572  104.895   0  0.0   
2       2  34.3447  15.18520  1400  42.8571  0.290601  576  104.167   0  0.0   
3       3  34.3421   8.84696  1400  42.8571  0.290601  576  104.167   0  0.0   
4       4  34.3322  14.69940  1400  42.8571  0.290601  576  104.167   0  0.0   

   ...     V2   V3       V4  V5    V6  V7    V8  V9  V10      V11  
0  ...  0.175  752  5.99375   0  2005   0  13.4   0    4  14.8004  
1  ...  0.455  752  5.99375   0  2007   0  13.4   0    4  14.7729  
2  ...  0.280  752  5.99375   0  2011   0  13.4   0    4  14.7736  
3  ...  0.070  752  5.99375   0  2015   0  13.4   0    4  14.7667  
4  ...  0.175  752  5.99375   0  2017   0  13.4   0    4  14.7757  

[5 rows x 31 columns]

In [95]:
y=train.loc[:,"IsAlert"]
y.head()

0    0
1    0
2    0
3    0
4    0
Name: IsAlert, dtype: int64

In [96]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [97]:
x_train.head()

ObsNum       P1        P2    P3        P4        P5   P6        P7  \
473076     434  35.1547  12.48300   988   60.7287  0.077839  584  102.7400   
251513     127  36.7000  17.87330   600  100.0000  0.313953  992   60.4839   
258822     196  33.6280   9.62824   984   60.9756  0.297087  832   72.1154   
237029     139  49.4695  10.14920  1000   60.0000  0.295790  948   63.2911   
69739      854  34.3921  16.69830   608   98.6842  0.079137  712   84.2697   

        P8      E1  ...     V2    V3       V4  V5    V6  V7    V8  V9  V10  \
473076   0   0.000  ...  0.000   496  3.01875   0  2048   0  17.6   0    4   
251513   0  31.835  ... -0.280   240  1.48750   0  2234   0  12.3   0    4   
258822   0   0.000  ... -0.665   767  1.48750   1  2371   0  20.8   0    4   
237029   0  32.862  ... -0.280   255  0.00000   0  2339   0  15.8   0    4   
69739    0   0.000  ...  0.000  1008  3.01875   0  2018   0  27.1   0    4   

             V11  
473076  12.55490  
251513  15.62450  
258822  14.93920  
237029  14.96720  
69739    9.12388  

[5 rows x 31 columns]

In [98]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [99]:
y_pred=lr.predict(x_test)

In [100]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

def pred(x,y):
  con_mat=confusion_matrix(x,y)
  accuracy=accuracy_score(x,y)
  report=classification_report(x,y)

  print(con_mat)
  print(accuracy)
  print(report)

In [101]:
pred(y_test,y_pred)

[[33491 17613]
 [16260 53502]]
0.7197474889547102
              precision    recall  f1-score   support

           0       0.67      0.66      0.66     51104
           1       0.75      0.77      0.76     69762

    accuracy                           0.72    120866
   macro avg       0.71      0.71      0.71    120866
weighted avg       0.72      0.72      0.72    120866



In [102]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier(criterion='gini',max_depth=5,min_samples_split=10)
dtc.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=5, min_samples_split=10)

In [103]:
y_pred_dtc=dtc.predict(x_test)

In [104]:
pred(y_test,y_pred_dtc)

[[39025 12079]
 [ 5968 63794]]
0.8506858835404497
              precision    recall  f1-score   support

           0       0.87      0.76      0.81     51104
           1       0.84      0.91      0.88     69762

    accuracy                           0.85    120866
   macro avg       0.85      0.84      0.84    120866
weighted avg       0.85      0.85      0.85    120866



In [105]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=100,random_state=2,min_samples_split=10)
rfc.fit(x_train,y_train)

RandomForestClassifier(min_samples_split=10, random_state=2)

In [106]:
y_pred_rfc=rfc.predict(x_test)

In [107]:
pred(y_test,y_pred_rfc)

[[49860  1244]
 [   66 69696]]
0.9891615508083332
              precision    recall  f1-score   support

           0       1.00      0.98      0.99     51104
           1       0.98      1.00      0.99     69762

    accuracy                           0.99    120866
   macro avg       0.99      0.99      0.99    120866
weighted avg       0.99      0.99      0.99    120866



# TEST DATA

In [108]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120840 entries, 0 to 120839
Data columns (total 33 columns):
 #   Column   Non-Null Count   Dtype  
---  ------   --------------   -----  
 0   TrialID  120840 non-null  int64  
 1   ObsNum   120840 non-null  int64  
 2   IsAlert  120840 non-null  object 
 3   P1       120840 non-null  float64
 4   P2       120840 non-null  float64
 5   P3       120840 non-null  int64  
 6   P4       120840 non-null  float64
 7   P5       120840 non-null  float64
 8   P6       120840 non-null  int64  
 9   P7       120840 non-null  float64
 10  P8       120840 non-null  int64  
 11  E1       120840 non-null  float64
 12  E2       120840 non-null  float64
 13  E3       120840 non-null  int64  
 14  E4       120840 non-null  int64  
 15  E5       120840 non-null  float64
 16  E6       120840 non-null  int64  
 17  E7       120840 non-null  int64  
 18  E8       120840 non-null  int64  
 19  E9       120840 non-null  int64  
 20  E10      120840 non-null  

In [109]:
test.drop("TrialID",axis=1,inplace=True)

In [110]:
x_t=test.drop("IsAlert",axis=1)
y_t=test.loc[:,"IsAlert"]

In [111]:
x_t.head()

ObsNum       P1       P2    P3    P4        P5   P6       P7  P8   E1  ...  \
0       0  38.4294  10.9435  1000  60.0  0.302277  508  118.110   0  0.0  ...   
1       1  38.3609  15.3212  1000  60.0  0.302277  508  118.110   0  0.0  ...   
2       2  38.2342  11.5140  1000  60.0  0.302277  508  118.110   0  0.0  ...   
3       3  37.9304  12.2615  1000  60.0  0.302277  508  118.110   0  0.0  ...   
4       4  37.8085  12.3666  1000  60.0  0.302277  504  119.048   0  0.0  ...   

     V2   V3       V4  V5    V6  V7    V8  V9  V10      V11  
0  0.00  255  4.50625   0  2127   0  17.6   0    4  16.1937  
1  0.00  255  4.50625   0  2127   0  17.6   0    4  16.1744  
2  0.07  255  4.50625   0  2131   0  17.6   0    4  16.1602  
3  0.07  255  4.50625   0  2131   0  17.6   0    4  16.1725  
4  0.00  255  4.50625   0  2136   0  17.6   0    4  16.1459  

[5 rows x 31 columns]

In [118]:
y_pred_test_lr=lr.predict(x_t)

In [119]:
y_pred_test_dtc=dtc.predict(x_t)

In [120]:
y_pred_test_rfc=rfc.predict(x_t)