In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
train=pd.read_csv("/content/fordTrain.csv")
test=pd.read_csv("/content/fordTest.csv")

In [4]:
train.head()

TrialID  ObsNum  IsAlert       P1        P2    P3       P4        P5   P6  \
0        0       0        0  34.7406   9.84593  1400  42.8571  0.290601  572   
1        0       1        0  34.4215  13.41120  1400  42.8571  0.290601  572   
2        0       2        0  34.3447  15.18520  1400  42.8571  0.290601  576   
3        0       3        0  34.3421   8.84696  1400  42.8571  0.290601  576   
4        0       4        0  34.3322  14.69940  1400  42.8571  0.290601  576   

        P7  ...     V2   V3       V4   V5      V6   V7    V8   V9  V10  \
0  104.895  ...  0.175  752  5.99375  0.0  2005.0  0.0  13.4  0.0  4.0   
1  104.895  ...  0.455  752  5.99375  0.0  2007.0  0.0  13.4  0.0  4.0   
2  104.167  ...  0.280  752  5.99375  0.0  2011.0  0.0  13.4  0.0  4.0   
3  104.167  ...  0.070  752  5.99375  0.0  2015.0  0.0  13.4  0.0  4.0   
4  104.167  ...  0.175  752  5.99375  0.0  2017.0  0.0  13.4  0.0  4.0   

       V11  
0  14.8004  
1  14.7729  
2  14.7736  
3  14.7667  
4  14.7757  

[5 rows x 33 columns]

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14637 entries, 0 to 14636
Data columns (total 33 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   TrialID  14637 non-null  int64  
 1   ObsNum   14637 non-null  int64  
 2   IsAlert  14637 non-null  int64  
 3   P1       14637 non-null  float64
 4   P2       14637 non-null  float64
 5   P3       14637 non-null  int64  
 6   P4       14637 non-null  float64
 7   P5       14637 non-null  float64
 8   P6       14637 non-null  int64  
 9   P7       14637 non-null  float64
 10  P8       14637 non-null  int64  
 11  E1       14637 non-null  float64
 12  E2       14637 non-null  float64
 13  E3       14637 non-null  int64  
 14  E4       14637 non-null  int64  
 15  E5       14637 non-null  float64
 16  E6       14637 non-null  int64  
 17  E7       14637 non-null  int64  
 18  E8       14637 non-null  int64  
 19  E9       14637 non-null  int64  
 20  E10      14637 non-null  int64  
 21  E11      146

In [6]:
train.isna().sum()

TrialID    0
ObsNum     0
IsAlert    0
P1         0
P2         0
P3         0
P4         0
P5         0
P6         0
P7         0
P8         0
E1         0
E2         0
E3         0
E4         0
E5         0
E6         0
E7         0
E8         0
E9         0
E10        0
E11        0
V1         0
V2         0
V3         0
V4         1
V5         1
V6         1
V7         1
V8         1
V9         1
V10        1
V11        1
dtype: int64

In [7]:
train=train.dropna()

In [8]:
train.drop("TrialID",axis=1,inplace=True)

In [9]:
print(train["IsAlert"].head())

0    0
1    0
2    0
3    0
4    0
Name: IsAlert, dtype: int64


In [10]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14636 entries, 0 to 14635
Data columns (total 32 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   ObsNum   14636 non-null  int64  
 1   IsAlert  14636 non-null  int64  
 2   P1       14636 non-null  float64
 3   P2       14636 non-null  float64
 4   P3       14636 non-null  int64  
 5   P4       14636 non-null  float64
 6   P5       14636 non-null  float64
 7   P6       14636 non-null  int64  
 8   P7       14636 non-null  float64
 9   P8       14636 non-null  int64  
 10  E1       14636 non-null  float64
 11  E2       14636 non-null  float64
 12  E3       14636 non-null  int64  
 13  E4       14636 non-null  int64  
 14  E5       14636 non-null  float64
 15  E6       14636 non-null  int64  
 16  E7       14636 non-null  int64  
 17  E8       14636 non-null  int64  
 18  E9       14636 non-null  int64  
 19  E10      14636 non-null  int64  
 20  E11      14636 non-null  float64
 21  V1       146

In [11]:
x=train.drop("IsAlert",axis=1)


In [12]:
x.head()

ObsNum       P1        P2    P3       P4        P5   P6       P7  P8   E1  \
0       0  34.7406   9.84593  1400  42.8571  0.290601  572  104.895   0  0.0   
1       1  34.4215  13.41120  1400  42.8571  0.290601  572  104.895   0  0.0   
2       2  34.3447  15.18520  1400  42.8571  0.290601  576  104.167   0  0.0   
3       3  34.3421   8.84696  1400  42.8571  0.290601  576  104.167   0  0.0   
4       4  34.3322  14.69940  1400  42.8571  0.290601  576  104.167   0  0.0   

   ...     V2   V3       V4   V5      V6   V7    V8   V9  V10      V11  
0  ...  0.175  752  5.99375  0.0  2005.0  0.0  13.4  0.0  4.0  14.8004  
1  ...  0.455  752  5.99375  0.0  2007.0  0.0  13.4  0.0  4.0  14.7729  
2  ...  0.280  752  5.99375  0.0  2011.0  0.0  13.4  0.0  4.0  14.7736  
3  ...  0.070  752  5.99375  0.0  2015.0  0.0  13.4  0.0  4.0  14.7667  
4  ...  0.175  752  5.99375  0.0  2017.0  0.0  13.4  0.0  4.0  14.7757  

[5 rows x 31 columns]

In [13]:
y=train.loc[:,"IsAlert"]
y.head()

0    0
1    0
2    0
3    0
4    0
Name: IsAlert, dtype: int64

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [15]:
x_train.head()

ObsNum       P1        P2    P3       P4        P5   P6       P7  P8  \
2259    1048  48.3595  14.91900  1268  47.3186  0.123246  664  90.3614   0   
6261     206  35.0761  12.42510  1620  37.0370  0.128435  648  92.5926   0   
6991     936  45.7584   9.72381  1444  41.5512  0.108975  644  93.1677   0   
2777     355  33.9505  15.09610   884  67.8733  0.114165  676  88.7574   0   
5477     633  34.5852   7.89248   872  68.8073  0.093407  720  83.3333   0   

          E1  ...     V2    V3        V4   V5      V6   V7    V8   V9  V10  \
2259  29.065  ...  0.000   752    1.4875  0.0  1756.0  0.0   0.0  0.0  4.0   
6261   0.000  ... -0.455   240  100.4940  0.0   645.0  0.0   0.0  0.0  1.0   
6991   0.000  ... -0.385   255  100.4940  0.0   636.0  0.0   0.0  0.0  1.0   
2777  15.123  ... -2.030  1022   52.5000  1.0  2314.0  0.0  29.7  0.0  2.0   
5477   0.012  ... -0.385   255  100.4940  0.0   635.0  0.0   0.0  0.0  1.0   

          V11  
2259  17.2770  
6261  15.8306  
6991  15.5001  
2777  16.4502  
5477  15.6718  

[5 rows x 31 columns]

In [16]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [17]:
y_pred=lr.predict(x_test)

In [18]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

def pred(x,y):
  con_mat=confusion_matrix(x,y)
  accuracy=accuracy_score(x,y)
  report=classification_report(x,y)

  print(con_mat)
  print(accuracy)
  print(report)

In [19]:
pred(y_test,y_pred)

[[ 897   91]
 [  41 1899]]
0.9549180327868853
              precision    recall  f1-score   support

           0       0.96      0.91      0.93       988
           1       0.95      0.98      0.97      1940

    accuracy                           0.95      2928
   macro avg       0.96      0.94      0.95      2928
weighted avg       0.95      0.95      0.95      2928



In [20]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier(criterion='gini',max_depth=5,min_samples_split=10)
dtc.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=5, min_samples_split=10)

In [21]:
y_pred_dtc=dtc.predict(x_test)

In [22]:
pred(y_test,y_pred_dtc)

[[ 934   54]
 [  11 1929]]
0.9778005464480874
              precision    recall  f1-score   support

           0       0.99      0.95      0.97       988
           1       0.97      0.99      0.98      1940

    accuracy                           0.98      2928
   macro avg       0.98      0.97      0.97      2928
weighted avg       0.98      0.98      0.98      2928



In [23]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=100,random_state=2,min_samples_split=10)
rfc.fit(x_train,y_train)

RandomForestClassifier(min_samples_split=10, random_state=2)

In [24]:
y_pred_rfc=rfc.predict(x_test)

In [25]:
pred(y_test,y_pred_rfc)

[[ 975   13]
 [   0 1940]]
0.9955601092896175
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       988
           1       0.99      1.00      1.00      1940

    accuracy                           1.00      2928
   macro avg       1.00      0.99      1.00      2928
weighted avg       1.00      1.00      1.00      2928



In [26]:
import xgboost as xgb

In [27]:
xgb_classifier=xgb.XGBClassifier(n_estimators=100,tree_method='hist')

In [28]:
xgb_classifier.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [29]:
y_pred_xgb_test=xgb_classifier.predict(x_test)

In [30]:
pred(y_test,y_pred_xgb_test)

[[ 981    7]
 [   0 1940]]
0.9976092896174863
              precision    recall  f1-score   support

           0       1.00      0.99      1.00       988
           1       1.00      1.00      1.00      1940

    accuracy                           1.00      2928
   macro avg       1.00      1.00      1.00      2928
weighted avg       1.00      1.00      1.00      2928



# TEST DATA

In [ ]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120840 entries, 0 to 120839
Data columns (total 33 columns):
 #   Column   Non-Null Count   Dtype  
---  ------   --------------   -----  
 0   TrialID  120840 non-null  int64  
 1   ObsNum   120840 non-null  int64  
 2   IsAlert  120840 non-null  object 
 3   P1       120840 non-null  float64
 4   P2       120840 non-null  float64
 5   P3       120840 non-null  int64  
 6   P4       120840 non-null  float64
 7   P5       120840 non-null  float64
 8   P6       120840 non-null  int64  
 9   P7       120840 non-null  float64
 10  P8       120840 non-null  int64  
 11  E1       120840 non-null  float64
 12  E2       120840 non-null  float64
 13  E3       120840 non-null  int64  
 14  E4       120840 non-null  int64  
 15  E5       120840 non-null  float64
 16  E6       120840 non-null  int64  
 17  E7       120840 non-null  int64  
 18  E8       120840 non-null  int64  
 19  E9       120840 non-null  int64  
 20  E10      120840 non-null  

In [ ]:
test.drop("TrialID",axis=1,inplace=True)

In [ ]:
x_t=test.drop("IsAlert",axis=1)
y_t=test.loc[:,"IsAlert"]

In [ ]:
x_t.head()

ObsNum       P1       P2    P3    P4        P5   P6       P7  P8   E1  ...  \
0       0  38.4294  10.9435  1000  60.0  0.302277  508  118.110   0  0.0  ...   
1       1  38.3609  15.3212  1000  60.0  0.302277  508  118.110   0  0.0  ...   
2       2  38.2342  11.5140  1000  60.0  0.302277  508  118.110   0  0.0  ...   
3       3  37.9304  12.2615  1000  60.0  0.302277  508  118.110   0  0.0  ...   
4       4  37.8085  12.3666  1000  60.0  0.302277  504  119.048   0  0.0  ...   

     V2   V3       V4  V5    V6  V7    V8  V9  V10      V11  
0  0.00  255  4.50625   0  2127   0  17.6   0    4  16.1937  
1  0.00  255  4.50625   0  2127   0  17.6   0    4  16.1744  
2  0.07  255  4.50625   0  2131   0  17.6   0    4  16.1602  
3  0.07  255  4.50625   0  2131   0  17.6   0    4  16.1725  
4  0.00  255  4.50625   0  2136   0  17.6   0    4  16.1459  

[5 rows x 31 columns]

In [ ]:
y_pred_test_lr=lr.predict(x_t)

In [ ]:
y_pred_test_dtc=dtc.predict(x_t)

In [ ]:
y_pred_test_rfc=rfc.predict(x_t)