In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
dataset=pd.read_csv("/content/data.csv")

In [5]:
print(dataset.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   origin               398 non-null    int64  
 1   cylinders            398 non-null    int64  
 2   displacement         398 non-null    float64
 3   horsepower           398 non-null    object 
 4   weight               398 non-null    int64  
 5   acceleration         398 non-null    float64
 6   year                 398 non-null    int64  
 7   name                 398 non-null    object 
 8   Kilometer_per_liter  398 non-null    float64
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB
None


In [16]:
import math
dataset["horsepower"]=dataset["horsepower"].replace(to_replace="?",value=0)

In [17]:
x=dataset.loc[0:,["cylinders","horsepower","acceleration","weight"]]

In [18]:
print(x)

     cylinders horsepower  acceleration  weight
0            8        130          12.0    3504
1            8        165          11.5    3693
2            8        150          11.0    3436
3            8        150          12.0    3433
4            8        140          10.5    3449
..         ...        ...           ...     ...
393          4         86          15.6    2790
394          4         52          24.6    2130
395          4         84          11.6    2295
396          4         79          18.6    2625
397          4         82          19.4    2720

[398 rows x 4 columns]


In [10]:
y=dataset.iloc[:,-1]
print(y)

0       7.652587
1       6.377156
2       7.652587
3       6.802299
4       7.227443
         ...    
393    11.478880
394    18.706323
395    13.604599
396    11.904024
397    13.179455
Name: Kilometer_per_liter, Length: 398, dtype: float64


In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [20]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [21]:
lr.predict(x_test)

array([ 6.05005732, 11.64391675,  6.08448562, 10.69659293,  9.15793447,
       14.13281874, 12.97063029, 12.09476455,  6.62940227, 10.15927209,
       14.18944662, 12.98772362, 10.05091091, 13.26157386,  6.17624191,
       12.88680175, 11.38343279, 11.11806547,  8.40138588, 12.49025688,
        5.10728736, 11.64796249, 11.4176955 , 10.03337396, 12.45148632,
        9.66196926, 13.31358641, 11.98824485, 11.51271119,  8.46307509,
        8.56724565, 11.53311484,  9.65886493, 13.16545645,  8.77268929,
       10.66420007,  9.60883356,  5.65376452, 12.90889165,  3.38554757,
        4.39749178,  6.86222114, 11.06221054, 11.33017276, 10.79910947,
       10.68302354,  9.98750902,  5.05856276, 10.97013775, 13.01254013,
       12.3856524 , 12.31919227,  6.06486499, 12.56203254,  6.97871096,
        5.17696587,  9.66191456, 10.01694278, 11.56081855,  7.61503436,
        9.24409082, 11.25601574, 10.3528972 , 10.3455392 ,  4.80333641,
        4.83227814,  4.75466475,  8.73354839, 11.32179828,  4.49

In [23]:
lr.predict([[8,130,12,3504]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([7.73581859])

In [24]:
lr.predict([[10,195,29,2500]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.18863476])